// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrm9be1QvXAX7ae1Pf9deGaPGxPWZ0s6c',
    appId: '1:574661066391:web:3da8a3a19d8a0a7aa3b3d2',
    messagingSenderId: '574661066391',
    projectId: 'todousingfirebase-412db',
    authDomain: 'todousingfirebase-412db.firebaseapp.com',
    storageBucket: 'todousingfirebase-412db.appspot.com',
    measurementId: 'G-GBC3YX17ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5To7k65vLFvp7hQXNbwy5vcslCsUZ5lI',
    appId: '1:574661066391:android:59cd1188b528c898a3b3d2',
    messagingSenderId: '574661066391',
    projectId: 'todousingfirebase-412db',
    storageBucket: 'todousingfirebase-412db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6tcEdNbobojKq1UiHjNXDyS_tPod02QE',
    appId: '1:574661066391:ios:ec82a9aef8793328a3b3d2',
    messagingSenderId: '574661066391',
    projectId: 'todousingfirebase-412db',
    storageBucket: 'todousingfirebase-412db.appspot.com',
    iosBundleId: 'com.example.firebasePractiseTodo',
  );
}
